name: odoo-experten-deutschland
region: fra
static_sites:
- name: web
  github:
    repo: LarryWalkerDEV/odoo-experten-deutschland
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  output_dir: out
  source_dir: /
  envs:
  - key: NODE_ENV
    value: production
    scope: BUILD_TIME
  - key: NEXT_PUBLIC_SITE_URL
    value: https://odoo-experten-deutschland.de
    scope: BUILD_TIME
  routes:
  - path: /
