name: odoo-experten-deutschland
region: fra
services:
- name: web
  github:
    repo: LarryWalkerDEV/odoo-experten-deutschland
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  run_command: npm start
  source_dir: /
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: NEXT_PUBLIC_SITE_URL
    value: https://odoo-experten-deutschland.de
    scope: RUN_AND_BUILD_TIME
  instance_size_slug: apps-s-1vcpu-0.5gb
  instance_count: 1
  http_port: 3000
